Resolve operations
houdamzari/Math-Magicians pull request #5
Opened 2023-01-11 19:46 UTC by houdamzari

- Added calculate and operate.js files.
- Added calculator's functionality.

2023-01-11 20:03 UTC, HAMMAS-SALEEM requested changes
# Required Changes :recycle:
![almost-there](https://user-images.githubusercontent.com/65860678/170491251-b1add8ba-b18f-4648-a893-20e510d957fd.gif)

## Hey @houdamzari :wave:

## Highlights :1st_place_medal:

✔️ Descriptive PR Title
✔️ Descriptive PR Summary
✔️ Following Gitflow
✔️ Following some requirements

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

# Optional

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-11 20:03 UTC, HAMMAS-SALEEM commented on src/components/Buttons.js
> -          <button type="button">7</button>
- [ ] All your events are working except divide event. Its because you didn't apply any eventlistener on this button  **&#247;** :fearful: Kindly put eventlistener to make it work :+1:

2023-01-11 20:03 UTC, HAMMAS-SALEEM commented on src/components/Buttons.js
>          <div className="mathOperations">
![image](https://user-images.githubusercontent.com/93039359/211905841-50ff35bc-afed-4058-933f-724816f96404.png)

- [ ] This link is not working. Kindly fix this link to make your readme file descriptive and professional :+1:

**Hint: You don't have a LICENSE file in your repository. Kindly add one using these [guidlines](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository) :+1:**

2023-01-13 14:04 UTC, fobadara approved these changes
Hi @houdamzari, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
✅ Linters are passing

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-01-13 14:09 UTC, merged

2023-01-13 14:14 UTC, houdamzari commented
@fobadara  Kindly mark my work as done so I can submit, because it still shows as ' Changes required' in my dashboard.

2023-01-13 14:42 UTC, AmaduKamara reviewed
# Status: Approved 🟢 🟢 🟢

Hi @houdamzari,

Your project is complete!  There is nothing else to say other than... it's time to merge it: ship it:
Congratulations! 🎉 

## Highlights:

✅ You used Gitflow correctly 👍🏽
✅ Linter checks passed 👍🏽
✅ All functionalities of the calculator app work fine as expected 👍🏽

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```